# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-US" # Used by the theme to translate dates and format strings.

title: Haotian's World Line # Your site title
title_separator: "|" # Your site title separator, defaults to "|"
name: "Haotian Wei" # Your name
email: weihaotian776@gmail.com
description: Haotian's blogging area
# Write an awesome description for your new site here. You can edit this
# line in _config.yml. It will appear in your document head meta (for
# Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://htwei17.github.io" # Your GitHub Pages URL
repository: "htwei17/htwei17.github.io"

twitter_username: htwei17
github_username: htwei17

author:
  name: "Haotian Wei"
  avatar: "/assets/images/bio.jpg"
  bio: "Many-body and everybody." # Note: Markdown is allowed
  location: "Harmonic Trap, Quantum"
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=mu--7-UAAAAJ"
    - label: "ORCID"
      icon: "fas fa-fw fa-link"
      url: "https://orcid.org/my-orcid?orcid=0000-0001-7684-2608"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/htwei17"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/htwei17"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll # You can change this if you're using a different theme
# "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "dark"

# Styling settings
teaser: /assets/images/fanjingshan.jpeg
logo: /assets/images/logo.png
masthead_title: Haotian's Wolrd Line

# Footer links
footer:
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=mu--7-UAAAAJ"
    - label: "ORCID"
      icon: "fas fa-fw fa-link"
      url: "https://orcid.org/my-orcid?orcid=0000-0001-7684-2608"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/htwei17"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/htwei17"

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single-math
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      sidebar:
        nav: main
      header:
        nav: main
        overlay_image: "/assets/images/SUN.png"
        overlay_filter: 0.5 # same as adding an opacity of 0.5 to a black background

# Features
search: true
atom_feed:
  hide: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
